[build]
  publish = "public"
  command = "npm run build"
  
[build.environment]
  NODE_VERSION = "12"

[[plugins]]
  package = "netlify-plugin-gatsby-cache"
  package = "gatsby-plugin-canonical-urls"

    [plugins.inputs]
    siteUrl = "https://mrekaya.com"